### ISSUE TITLE
Porous media

### ISSUE THREAD

**Issue by MehdiMahdaviara** [Ceyron/numeric-notes#13]
May I please ask if your code has the capability to be customized for porous media geometry as it is quite common to simulate fluid flow in porous media? The geometry can be achieved from micro-CT images. Thank you.

**Comment by Ceyron** [comment]
Hi,

thanks for the question and sorry for the late reply.
I do not have much experience with Darcy flow simulations. Probably, the CFD files under simulation_scripts cannot easily be adapted.
One alternative would be to use FEniCs: https://fenicsproject.org/olddocs/dolfin/2016.2.0/python/demo/documented/mixed-poisson/python/demo_mixed-poisson.py.html
