### ISSUE TITLE
Dynamic Boundary Condition in PINNs

### ISSUE THREAD

**Issue by svkarash** [Ceyron/numeric-notes#16]
Dear @Ceyron 
I am dealing with a fluid dynamics problem involving a water tank, surface waves, and a set of partial differential equations (PDEs) along with boundary conditions. I am interested in using Physics Informed Neural Networks particularly DeepXDE library to solve this system, but I encountered issues with definition of boundary conditions and initial conditions. 
the code and explanation are available in the link below. I would appreciate it if you could take a look at the problem. 

https://github.com/lululxvi/deepxde/issues/1565

**Comment by Ceyron** [comment]
Hi @svkarash,
I'm afraid I am not familiar with the DeepXDE library and can't help you with your problem. I am sorry.
