### ISSUE TITLE
ODE Optimal Control as an aside derivation from the adjoint sensitivity by lagrange method

### ISSUE THREAD

**Issue by shayshay42** [Ceyron/numeric-notes#17]
Hi @Ceyron 

I love the videos!
Wrote up the derivation for the ODE adjoints and wrote a derivation for getting gradients for an optimal controller u(t) that influences the ODEs.
I'm working on the derivation for the adjoint of a hybrid ODE system with events.
Let me know if these would be useful additions to the notes for viewers and I can open a pull request!

Thanks,
Shayan

[sensitivity.pdf](https://github.com/Ceyron/machine-learning-and-simulation/files/14152574/sensitivity.pdf)

**Comment by Ceyron** [comment]
Hi Shayan,

Excellent job writing that up  👍. I think that could be a good topic for your first blog post? Would be nice to also have derivation of these topics in nice HTML quality. Would be happy to link to it from the video once. :)

**Comment by shayshay42** [comment]
This is a great idea! Will be in touch...
