### ISSUE TITLE
Can you make a DOI for this repository so that it is easier to cite?

### ISSUE THREAD

**Issue by sibocw** [Ceyron/numeric-notes#18]
Hello, thank you for putting this up! I'm wondering if you can get a DOI for this repo so that it can be cited more easily in research papers? _Nature Methods_, for example, has a policy that only entries with DOIs or preprints can be referenced; URLs for web sites should be cited parenthetically in the main text, not in the reference list ([source](https://www.nature.com/nmeth/submission-guidelines/aip-and-formatting#references)).

Information on how to get a DOI via Zenodo: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Thank you very much!

**Comment by Ceyron** [comment]
Hi,
Yes, it could be a great thing to add. :+1:. I just added the first Zenodo tag.
I will have to figure out how to handle the tagging over time as it is not a software package repo but rather a dump/storage for the channel's material. It's probably unreasonable to create a new tag for every new video. Do you have a good idea about that?

**Comment by sibocw** [comment]
Hi, thank you for the prompt response!

If I understand correctly, I don't think it's a bad idea to simply tag the whole repo as a piece of "software," and rely on version control as usual in case of additional materials? Zenodo issues a new DOI for each new version as well as a generic DOI for the whole repository. The following is a screenshot from the Zenodo page:
<img width="378" alt="image" src="https://github.com/user-attachments/assets/282dec5a-818b-4dba-9bae-182e67365583">

It might also make sense to update the CITATION.cff file to include the DOI. Let me know if you want me to make a PR for this.

**Comment by Ceyron** [comment]
Cool, then it makes sense to have the general DOI ending on 323 linked in the README.md and the CITATION.cff. Feel free to open a PR for that :+1: 

> If I understand correctly, I don't think it's a bad idea to simply tag the whole repo as a piece of "software," and rely on version control as usual in case of additional materials? Zenodo issues a new DOI for each new version as well as a generic DOI for the whole repository. The following is a screenshot from the Zenodo page:

As far as I understand, Zenodo creates a new DOI for each new release/tag of the repository. To have the DOI include the material of the most recent video, I would have to tag each new upload, right? I'm unsure if this is the right solution. What do you think?

**Comment by sibocw** [comment]
> Cool, then it makes sense to have the general DOI ending on 323 linked in the README.md and the CITATION.cff. Feel free to open a PR for that 👍

Done!

> As far as I understand, Zenodo creates a new DOI for each new release/tag of the repository. To have the DOI include the material of the most recent video, I would have to tag each new upload, right? I'm unsure if this is the right solution. What do you think?

Ah, I see. Personally I don't think it's bad to have more frequent tags (aside from, of course, the fact that you'd have to create those tags). Practically it probably doesn't make a difference — I think most people will discover this repo on GitHub anyway. As long as there's a version-agnostic DOI to cite, I think it should be good.

**Comment by Ceyron** [comment]
Great, thanks for the input :+1: 

I will try to have occasional tags.

**Comment by sibocw** [comment]
Sounds great, thanks again for putting this up! It's very helpful.

**Comment by Ceyron** [comment]
Thanks a lot :heart:
